# GENERATED CONTENT
# remove repo from adrianjost/.github/synced/workflows/generator.js before editing
name: PR Automation
'on':
  issue_comment:
    types:
      - created
jobs:
  dependabot-recreate:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: Someone with write access should tell dependabot to recreate this PR.
        env:
          GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
        id: prcomm
      - name: tell dependabot to recreate pr
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
          issue-number: '${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}'
          body: '@dependabot recreate'
